### ISSUE TITLE
failed imports

### ISSUE THREAD

**Issue by cfhaak** [bundesverfassung-oesterreich/bv-transkribus-import#12]
In some cases the recent reimport (#10) failed.
It seems the problem is caused by goobi not providing uniform files for some unknown reason.
If images get referenced like that, the import fails: 
```xml
<mets:div ID="PHYS_0020" ORDER="20" ORDERLABEL="19" TYPE="page">
    <mets:fptr FILEID="FILE_0020_PRESENTATION"/>
    <mets:fptr FILEID="FILE_0020_DEFAULT"/>
</mets:div>
```
Here it works.
```xml
<mets:div ID="PHYS_0004" ORDER="4" ORDERLABEL=" - " TYPE="page">
    <mets:fptr FILEID="FILE_0004"/>
    <mets:fptr FILEID="FILE_0004_PRESENTATION"/>
    <mets:fptr FILEID="FILE_0004_DEFAULT"/>
</mets:div>
```
Reason is the missing standard file-ptr in the mets. I probably could fix this, by just adding them to the file, since the corresponding files seem to exist. In some cases the files are even containing both kinds of links, faulty and working ones.
Ich however will rather try to republish them in goobi.

**Comment by cfhaak** [comment]
On second thought: maybe fixing the mets on the fly isn't a bad idea if it works, since it isn't easy to decide, if an import worked without opening the document in the collection, due to the fact, that mets can be partially corrupted.

**Comment by cfhaak** [comment]
- [x] identify faulty imports
- [x] delete them
- [x] republish them in goobi
- [x] reimport them

**Comment by cfhaak** [comment]
Set A:
B-VG saubere Varaiante

Set B:
Protokoll 7. Laenderkonferenz: bv_doc_id__61
Protokoll 6. Laenderkonferenz: bv_doc_id__60
Protokoll 4. Laenderkonferenz: bv_doc_id__59
Protokoll 3. Laenderkonferenz: bv_doc_id__58
Protokoll der 4. Sitzung des Subkomitees des Verfassungsausschusses vom 22. Juli 1920: bv_doc_id__39
Protokoll 2. Laenderkonferenz 4. und 5. Jänner 1919 (partial): bv_doc_id__57
Protokoll 1. Laenderkonferenz 23. November 1918 (partial): bv_doc_id__56

It's possible that there are more partially failed imports, but this is enough to test, if I can fix this in the fly by adding the links to the mets file.

**Comment by cfhaak** [comment]
I republished theses images to the viewer in goobi as suggested, and reimported them, but this didn't solve the issue.

**Comment by cfhaak** [comment]
Since one of the documents allready imported and transcribed was not cropped but the default upload (one image even with turned 180 degrees): @csae8092 are we supposed to use the defaults or the cropped ones for transcribing?

**Comment by csae8092** [comment]
Ideally those Images which will be archived in arche

**Comment by cfhaak** [comment]
should import cropped images, need to investigate how import currently works with given packaged

**Comment by cfhaak** [comment]
this is the case, howerver some images are not cropped in goobi

**Comment by cfhaak** [comment]
it seems as if all issues are caused by goobi-workflows & need to be further investigated there

**Comment by cfhaak** [comment]
Set A:
- [x]  BV-VG saubere Varaiante (could reimport but messed up the cropping)
- [ ]  Kelsen I - was exported but the wrong version. Enough to be worked with, but 1 page was messed up and needs to be transkribed later. The workflow is stuck with an error I cant fix, Daniel might take care of this.
- [ ] Grossdeutsch Sonderdruck Textvariante 2 (not cropped)
- [ ] Mayr I Druck saubere Variante  (not cropped)
- [ ]  Grossdeutsch Sonderdruck Textvariante 1 (n.c.)
- [ ] Grossdeutsch Sonderdruck Textvariante 2 (n.c.)
- [ ] CS I KNV-Beilage (n.c.)
(might [be](![grafik](https://github.com/bundesverfassung-oesterreich/bv-transkribus-import/assets/53819541/58e1ba02-7ca8-4d37-a8f2-a4b4da63c719)) more)

Set B:
- [ ]  Protokoll 7. Laenderkonferenz: bv_doc_id__61
- [ ]  Protokoll 6. Laenderkonferenz: bv_doc_id__60
- [ ]  Protokoll 4. Laenderkonferenz: bv_doc_id__59
- [ ]  Protokoll 3. Laenderkonferenz: bv_doc_id__58
- [ ]  Protokoll der 4. Sitzung des Subkomitees des Verfassungsausschusses vom 22. Juli 1920: bv_doc_id__39
- [ ]  Protokoll 2. Laenderkonferenz 4. und 5. Jänner 1919 (partial): bv_doc_id__57
- [ ]  Protokoll 1. Laenderkonferenz 23. November 1918 (partial): bv_doc_id__56
- [x] Bericht 5. Länderkonferenz 1920
![grafik](https://github.com/bundesverfassung-oesterreich/bv-transkribus-import/assets/53819541/1133eeae-6a05-4fb3-9399-7f55c176649c)

**Comment by cfhaak** [comment]
Still need to solve some of them, only way to do this is in goobi, since the processes there where messed up or failed due to the rather fragile systems. I will fix myself as long Jörg is on vacation, but on the long run, this should be handled by someone else.
