### ISSUE TITLE
csv for goobi-ids

### ISSUE THREAD

**Issue by csae8092** [bundesverfassung-oesterreich/bv-transkribus-import#3]
provide a basic csv to collect goobi ids of documents which should be imported into transkribus; ideally add the date of ingest

**Comment by cfhaak** [comment]
collect from baserow

**Comment by cfhaak** [comment]
This is now handeld by the ingest script. It imports documents
1. that have a collection id in the goobi db
2. that have no doc id in the goobi db
3. if doc_title is not present in target collection (from 1)
